Repository mesosphere/marathon, pull requests merged in 2018-04, with the labels that each got.

#6046 Send Instance health changed event when the overall status changed
  benchmark/src/main/scala/mesosphere/marathon/core/health/impl/AppHealthCheckBenchmark.scala
  src/main/scala/mesosphere/marathon/core/health/impl/AppHealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala
  src/test/scala/mesosphere/marathon/core/health/impl/AppHealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManagerTest.scala
Labels: community

#6132 Send Instance health changed event when the overall status Backport
  benchmark/src/main/scala/mesosphere/marathon/core/health/impl/AppHealthCheckBenchmark.scala
  src/main/scala/mesosphere/marathon/core/health/impl/AppHealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala
  src/test/scala/mesosphere/marathon/core/health/impl/AppHealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManagerTest.scala
Labels: backport, backport-1.5, community

#6135 Back-port SlidingAverageSnapshot fix for metrics
  docs/docs/command-line-flags.md
  docs/docs/metrics.md
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/metrics/Metrics.scala
  src/main/scala/mesosphere/marathon/metrics/MetricsReporterConf.scala
  src/main/scala/mesosphere/marathon/metrics/SlidingAverageSnapshot.scala
  src/test/scala/mesosphere/marathon/metrics/SlidingAverageSnapshotTest.scala
Labels: backport-1.5

#6138 Fix leaked process assertion in the pipeline script
  ci/pipeline
  ci/utils.sc
Labels: small and cute

#6137 Decrease archived IT sandbox size by excluding `provisioner` folders from the tarball
  ci/pipeline
Labels: hold merge

#6144 Stabilize `MesosAppIntegrationTest`
  src/test/scala/mesosphere/marathon/integration/MesosAppIntegrationTest.scala
Labels: small and cute

#6150 Minor fix to the AMI documentation
  ami/AMI.md
Labels: last one merges

#6148 Docs several broken links fixes
  docs/_layouts/default.html
  docs/docs/auth-access-ctrl.md
  docs/docs/deployments.md
  docs/docs/fault-domain-awareness.md
  docs/docs/generated/api.md
  docs/docs/native-docker-private-registry.md
  docs/docs/networking.md
  docs/docs/persistent-volumes.md
  docs/docs/pods.md
  docs/docs/preferential-gpu-scheduling.md
  docs/docs/secrets.md
  docs/docs/service-discovery-load-balancing.md
  docs/docs/task-handling.md
  docs/docs/upgrade/index.md
  docs/index.md
Labels: documentation, small and cute

#6145 Pod failure reasons are not visible in the UI/API
  src/main/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseData.scala
  src/test/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseDataTest.scala
  src/test/scala/mesosphere/marathon/state/TaskFailureTest.scala
  src/test/scala/mesosphere/marathon/state/TaskFailureTestHelper.scala
Labels: small and cute

#6161 Update documentation for unreachable tasks
  docs/docs/unreachable.md
Labels: community, documentation

#6165 Fix for a flaky test_unhealthy_app_can_be_rolled_back
  tests/system/common.py
  tests/system/marathon_common_tests.py
Labels: small and cute

#6169 Retry secret env var fetching in system test.
  tests/system/test_marathon_root.py
Labels: last one merges
