Repository mesosphere/marathon, pull requests merged in 2018-08, with the labels that each got.

#6208 Do not leak ZK credentials in /v2/info
  benchmark/src/main/scala/mesosphere/marathon/core/storage/zookeeper/ZooKeeperPersistenceStoreBenchmark.scala
  changelog.md
  src/main/scala/mesosphere/marathon/MarathonConf.scala
  src/main/scala/mesosphere/marathon/MarathonModule.scala
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerDriver.scala
  src/main/scala/mesosphere/marathon/ZookeeperConf.scala
  src/main/scala/mesosphere/marathon/api/v2/InfoResource.scala
  src/main/scala/mesosphere/marathon/core/election/CuratorElectionStream.scala
  src/main/scala/mesosphere/marathon/core/election/ElectionModule.scala
  src/main/scala/mesosphere/marathon/storage/StorageConfig.scala
  src/test/scala/mesosphere/marathon/MarathonConfTest.scala
  src/test/scala/mesosphere/marathon/ZookeeperConfTest.scala
  src/test/scala/mesosphere/marathon/api/v2/InfoResourceTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/core/election/CuratorElectionStreamTest.scala
Labels: needs backport

#6410 Increase timeout for the `test_external_volume` test
  tests/system/test_marathon_root.py
Labels: last one merges, small and cute

#6417 Remove colored console output in production
  src/main/resources/logback.xml
Labels: last one merges, small and cute

#6213 Properly forward HTTP requests which are expected to have body
  src/main/scala/mesosphere/marathon/api/forwarder/JavaUrlConnectionRequestForwarder.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/ForwardToLeaderIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/AppMockFacade.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/ForwarderService.scala
Labels: needs backport

#6435 Crash if ZK DNS is not resolvable (#6412)
  benchmark/src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPresistenceStoreBenchmark.scala
  benchmark/src/main/scala/mesosphere/marathon/core/storage/zookeeper/ZooKeeperPersistenceStoreBenchmark.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/storage/backup/Backup.scala
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/RichCuratorFramework.scala
  src/main/scala/mesosphere/marathon/storage/StorageConfig.scala
  src/main/scala/mesosphere/marathon/storage/StorageModule.scala
  src/test/scala/mesosphere/marathon/util/ZookeeperServer.scala
Labels: backport-1.6

#6439 Properly forward HTTP requests which are expected to have body (#6213)
  src/main/scala/mesosphere/marathon/api/forwarder/JavaUrlConnectionRequestForwarder.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/ForwardToLeaderIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/AppMockFacade.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/ForwarderService.scala
Labels: backport-1.6

#6268 Properly forward HTTP requests which are expected to have body
  src/main/scala/mesosphere/marathon/api/LeaderProxyFilter.scala
  src/test/scala/mesosphere/marathon/integration/ForwardToLeaderIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/setup/AppMockFacade.scala
  src/test/scala/mesosphere/marathon/integration/setup/ForwarderService.scala
Labels: backport-1.5

#6445 Fix broken offer rejection statistics when maintenance mode is enabled
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
Labels: needs backport, small and cute

#6446 Fix broken offer rejection statistics when maintenance mode is enable…
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
Labels: backport-1.6

#6447 Add `DCOS_PACKAGE_NAME` to our custom framework definition in SI tests
  tests/system/apps/fake-framework.json
Labels: last one merges, small and cute

#6456 nit: renamed deprecatedMetrics.md to deprecated-metrics.md
  docs/_layouts/docs.html
  docs/docs/deprecated-metrics.md
  docs/index.md
Labels: yolo

#6459 Time out long-running jobs
  tests/performance/live.sh
Labels: yolo

#6468 Removed SI MoM-EE tests for disabled security mode
  tests/system/fixtures/mom-ee-disabled-1.4.json
  tests/system/fixtures/mom-ee-disabled-1.5.json
  tests/system/test_marathon_on_marathon_ee.py
Labels: last one merges

#6470 Import dcos/dcos-cli@46463a3.
  ci/si_install_deps.sh
  tests/shakedown/dcos/__init__.py
  tests/shakedown/dcos/auth.py
  tests/shakedown/dcos/cluster.py
  tests/shakedown/dcos/cmds.py
  tests/shakedown/dcos/config.py
  tests/shakedown/dcos/constants.py
  tests/shakedown/dcos/cosmos.py
  tests/shakedown/dcos/data/config-schema/cluster.json
  tests/shakedown/dcos/data/config-schema/core.json
  tests/shakedown/dcos/data/config-schema/job.json
  tests/shakedown/dcos/data/config-schema/marathon.json
  tests/shakedown/dcos/data/config-schema/package.json
  tests/shakedown/dcos/data/marathon/error.schema.json
  tests/shakedown/dcos/emitting.py
  tests/shakedown/dcos/errors.py
  tests/shakedown/dcos/http.py
  tests/shakedown/dcos/jsonitem.py
  tests/shakedown/dcos/marathon.py
  tests/shakedown/dcos/mesos.py
  tests/shakedown/dcos/metronome.py
  tests/shakedown/dcos/options.py
  tests/shakedown/dcos/package.py
  tests/shakedown/dcos/packagemanager.py
  tests/shakedown/dcos/recordio.py
  tests/shakedown/dcos/rpcclient.py
  tests/shakedown/dcos/servicemanager.py
  tests/shakedown/dcos/sse.py
  tests/shakedown/dcos/subcommand.py
  tests/shakedown/dcos/subprocess.py
  tests/shakedown/dcos/util.py
  tests/shakedown/requirements.txt
  tests/shakedown/setup.py
  tests/system/Pipfile.lock
Labels: iken

#6477 Fix a rare race condition in `MarathonHealthCheckManager`
  src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala
Labels: nano

#6469 Indicate suicide reason with exit code.
  docs/_layouts/docs.html
  docs/docs/exit-codes.md
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
  src/main/scala/mesosphere/marathon/core/base/RichRuntime.scala
  src/main/scala/mesosphere/marathon/core/election/ElectionService.scala
  src/main/scala/mesosphere/marathon/core/plugin/impl/PluginManagerImpl.scala
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/RichCuratorFramework.scala
  src/main/scala/mesosphere/marathon/storage/StorageConfig.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerTest.scala
  src/test/scala/mesosphere/marathon/test/TestCrashStrategy.scala
  src/test/scala/mesosphere/marathon/util/ZookeeperServer.scala
Labels: needs backport

#6478 Address a compiler warning and fix formatting
  src/main/scala/mesosphere/marathon/state/AppDefinition.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/MesosAppIntegrationTest.scala
Labels: yolo

#6483 Fix a typo
  src/main/scala/mesosphere/marathon/metrics/MetricsConf.scala
  src/main/scala/mesosphere/marathon/metrics/current/DropwizardMetricsModule.scala
Labels: yolo

#6487 Append .metric to meter metric names
  docs/docs/metrics.md
  src/main/java/mesosphere/marathon/metrics/current/InstrumentedHandler.java
Labels: yolo

#6488 Add meter() to Metrics API
  src/main/scala/mesosphere/marathon/metrics/Metrics.scala
  src/main/scala/mesosphere/marathon/metrics/current/DropwizardMetrics.scala
  src/main/scala/mesosphere/marathon/metrics/deprecated/KamonMetrics.scala
  src/main/scala/mesosphere/marathon/metrics/dummy/DummyMetrics.scala
Labels: yolo

#6489 Make sure concurrency is bound all over the migration code
  src/main/scala/mesosphere/marathon/storage/migration/MigrationTo1_4_PersistenceStore.scala
  src/main/scala/mesosphere/marathon/storage/migration/legacy/MigrationTo0_16.scala
  src/main/scala/mesosphere/marathon/storage/migration/legacy/MigrationTo1_1_5.scala
  src/main/scala/mesosphere/marathon/storage/migration/legacy/MigrationTo1_2.scala
  src/main/scala/mesosphere/marathon/storage/migration/legacy/MigrationTo_1_4_0.scala
Labels: yolo

#6490 Update changelog for 1.4.13 release
  changelog.md
Labels: yolo

#6486 Document new exit codes in changelog.
  changelog.md
Labels: needs backport

#6481 Indicate suicide reason with exit code. (#6469)
  docs/_layouts/docs.html
  docs/docs/exit-codes.md
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
  src/main/scala/mesosphere/marathon/core/base/RichRuntime.scala
  src/main/scala/mesosphere/marathon/core/election/ElectionService.scala
  src/main/scala/mesosphere/marathon/core/plugin/impl/PluginManagerImpl.scala
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/RichCuratorFramework.scala
  src/main/scala/mesosphere/marathon/storage/StorageConfig.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerTest.scala
  src/test/scala/mesosphere/marathon/test/TestCrashStrategy.scala
  src/test/scala/mesosphere/marathon/util/ZookeeperServer.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
Labels: backport-1.6

#6494 Update links to point to 1.4.13 release
  docs/index.md
Labels: yolo

#6460 Checking unreachable behaviour for pods when wipe=true
  tests/integration/src/test/scala/mesosphere/marathon/integration/TaskUnreachableIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/facades/MarathonFacade.scala
Labels: wip

#6287 Update Marathon-ui to version 1.3.1
  changelog.md
  project/Dependencies.scala
Labels: backport-1.4, backport-1.5, backport-1.6
