Repository mesosphere/marathon, pull requests merged in 2018-10, with the labels that each got.

#6574 Be conservative when creating new framework IDs
  changelog.md
  docs/docs/exit-codes.md
  docs/docs/framework-id.md
  src/main/scala/mesosphere/marathon/MarathonModule.scala
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/main/scala/mesosphere/marathon/SchedulerDriverFactory.scala
  src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerTest.scala
  src/test/scala/mesosphere/marathon/SchedulerDriverFactoryTest.scala
  src/test/scala/mesosphere/marathon/storage/repository/RepositoryTest.scala
  src/test/scala/mesosphere/marathon/test/TestCrashStrategy.scala
Labels: needs backport

#6581 Default for unreachable strategy on PUT /apps (#6556)
  src/main/scala/mesosphere/marathon/api/v2/AppHelpers.scala
  src/test/scala/mesosphere/marathon/api/v2/json/AppUpdateTest.scala
Labels: backport-1.6

#6584 Clean sbt integration test project.
  ci/pipeline
Labels: needs backport, yolo

#6582 Default for unreachable strategy on PUT /apps
  src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala
  src/test/scala/mesosphere/marathon/api/v2/json/AppUpdateTest.scala
Labels: backport-1.5

#6587 Enable merge union strategy for changelog.md
  .gitattributes
Labels: backport-1.5

#6589 Enable merge union strategy for changelog.md
  .gitattributes
Labels: backport-1.7

#6588 Enable merge union strategy for changelog.md
  .gitattributes
Labels: backport-1.6

#6577 Be conservative when creating new framework IDs
  changelog.md
  docs/docs/exit-codes.md
  docs/docs/framework-id.md
  src/main/scala/mesosphere/marathon/MarathonModule.scala
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/main/scala/mesosphere/marathon/SchedulerDriverFactory.scala
  src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerTest.scala
  src/test/scala/mesosphere/marathon/SchedulerDriverFactoryTest.scala
  src/test/scala/mesosphere/marathon/test/TestCrashStrategy.scala
Labels: backport-1.6

#6578 Be conservative when creating new framework IDs
  changelog.md
  docs/docs/framework-id.md
  src/main/scala/mesosphere/marathon/MarathonModule.scala
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/main/scala/mesosphere/marathon/SchedulerDriverFactory.scala
  src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerTest.scala
  src/test/scala/mesosphere/marathon/SchedulerDriverFactoryTest.scala
  src/test/scala/mesosphere/marathon/test/TestCrashStrategy.scala
Labels: backport-1.5

#6592 Fix for broken versioning of Apps and Pods (#6558)
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStore.scala
  src/main/scala/mesosphere/marathon/raml/DefaultConversions.scala
  src/main/scala/mesosphere/marathon/state/Timestamp.scala
  src/main/scala/mesosphere/marathon/storage/repository/DeploymentRepositoryImpl.scala
  src/main/scala/mesosphere/marathon/storage/repository/GroupRepositoryImpl.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/state/TimestampTest.scala
Labels: backport-1.7

#6593 Fix for broken versioning of Apps and Pods (#6558)
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStore.scala
  src/main/scala/mesosphere/marathon/raml/DefaultConversions.scala
  src/main/scala/mesosphere/marathon/state/Timestamp.scala
  src/main/scala/mesosphere/marathon/storage/repository/DeploymentRepositoryImpl.scala
  src/main/scala/mesosphere/marathon/storage/repository/GroupRepositoryImpl.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/state/TimestampTest.scala
Labels: backport-1.6

#6597 Construct task ids from instance ids.
  src/main/scala/mesosphere/marathon/core/launcher/impl/InstanceOpFactoryImpl.scala
  src/main/scala/mesosphere/marathon/core/task/Task.scala
  src/test/scala/mesosphere/marathon/api/EndpointsHelperTest.scala
  src/test/scala/mesosphere/marathon/api/v2/SpecInstancesResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/TasksResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/json/EnrichedTaskWritesTest.scala
  src/test/scala/mesosphere/marathon/api/v2/json/ReadinessCheckResultFormatTest.scala
  src/test/scala/mesosphere/marathon/core/appinfo/TaskCountsTest.scala
  src/test/scala/mesosphere/marathon/core/appinfo/TaskLifeTimeTest.scala
  src/test/scala/mesosphere/marathon/core/appinfo/TaskStatsByVersionTest.scala
  src/test/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseDataTest.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/ReadinessBehaviorTest.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/TaskReplaceActorTest.scala
  src/test/scala/mesosphere/marathon/core/health/HealthTest.scala
  src/test/scala/mesosphere/marathon/core/health/MesosHealthCheckTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManagerTest.scala
  src/test/scala/mesosphere/marathon/core/history/impl/HistoryActorTest.scala
  src/test/scala/mesosphere/marathon/core/instance/InstanceStateTest.scala
  src/test/scala/mesosphere/marathon/core/instance/InstanceTest.scala
  src/test/scala/mesosphere/marathon/core/instance/TestTaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/instance/update/InstanceUpdateOpResolverTest.scala
  src/test/scala/mesosphere/marathon/core/instance/update/InstanceUpdaterTest.scala
  src/test/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImplTest.scala
  src/test/scala/mesosphere/marathon/core/launcher/impl/TaskLabelsTest.scala
  src/test/scala/mesosphere/marathon/core/launcher/impl/TaskLauncherImplTest.scala
  src/test/scala/mesosphere/marathon/core/launchqueue/impl/TaskLauncherActorTest.scala
  src/test/scala/mesosphere/marathon/core/matcher/base/util/OfferOperationFactoryTest.scala
  src/test/scala/mesosphere/marathon/core/matcher/manager/impl/OfferMatcherManagerModuleTest.scala
  src/test/scala/mesosphere/marathon/core/matcher/reconcile/impl/OfferMatcherReconcilerTest.scala
  src/test/scala/mesosphere/marathon/core/readiness/ReadinessCheckResultTest.scala
  src/test/scala/mesosphere/marathon/core/readiness/impl/ReadinessCheckExecutorImplTest.scala
  src/test/scala/mesosphere/marathon/core/task/TaskTest.scala
  src/test/scala/mesosphere/marathon/core/task/bus/TaskStatusUpdateTestHelper.scala
  src/test/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActorTest.scala
  src/test/scala/mesosphere/marathon/instance/InstanceIdTest.scala
  src/test/scala/mesosphere/marathon/raml/PodStatusConversionTest.scala
  src/test/scala/mesosphere/marathon/storage/migration/MigrationTo160Test.scala
  src/test/scala/mesosphere/marathon/storage/migration/MigrationTo17Test.scala
  src/test/scala/mesosphere/marathon/tasks/InstanceOpFactoryHelperTest.scala
  src/test/scala/mesosphere/marathon/tasks/InstanceOpFactoryImplTest.scala
  src/test/scala/mesosphere/marathon/tasks/InstanceTrackerImplTest.scala
  src/test/scala/mesosphere/marathon/tasks/TaskIdTest.scala
  src/test/scala/mesosphere/marathon/test/MarathonTestHelper.scala
  src/test/scala/mesosphere/mesos/PersistentVolumeMatcherTest.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
  src/test/scala/mesosphere/mesos/TaskBuilderTest.scala
Labels: last one merges

#6601 Write out correct version in ZkId.
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStore.scala
  src/main/scala/mesosphere/marathon/raml/DefaultConversions.scala
  src/main/scala/mesosphere/marathon/state/Timestamp.scala
  src/main/scala/mesosphere/marathon/storage/repository/DeploymentRepositoryImpl.scala
  src/main/scala/mesosphere/marathon/storage/repository/GroupRepositoryImpl.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/state/TimestampTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/facades/MarathonFacade.scala
Labels: needs backport

#6605 Write out correct version in ZkId. (#6601)
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStore.scala
  src/main/scala/mesosphere/marathon/raml/DefaultConversions.scala
  src/main/scala/mesosphere/marathon/state/Timestamp.scala
  src/main/scala/mesosphere/marathon/storage/repository/DeploymentRepositoryImpl.scala
  src/main/scala/mesosphere/marathon/storage/repository/GroupRepositoryImpl.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/state/TimestampTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/facades/MarathonFacade.scala
Labels: backport-1.7

#6606 Write out correct version in ZkId. (#6601)
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStore.scala
  src/main/scala/mesosphere/marathon/raml/DefaultConversions.scala
  src/main/scala/mesosphere/marathon/state/Timestamp.scala
  src/main/scala/mesosphere/marathon/storage/repository/DeploymentRepositoryImpl.scala
  src/main/scala/mesosphere/marathon/storage/repository/GroupRepositoryImpl.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/state/TimestampTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/facades/MarathonFacade.scala
Labels: backport-1.6

#6595 Only log zero-value offers for scalar resources and ranges
  src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala
Labels: needs backport

#6596 `TaskOverdueActor` now respects `--kill_retry_timeout` parameter
  changelog.md
  docs/docs/metrics.md
  src/main/scala/mesosphere/marathon/MarathonSchedulerActor.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/TaskJobsModule.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/KillConfig.scala
  src/main/scala/mesosphere/marathon/core/task/termination/KillService.scala
  src/main/scala/mesosphere/marathon/core/task/termination/TaskTerminationModule.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceDelegate.scala
  src/test/scala/mesosphere/marathon/SchedulerActionsTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/instance/TestTaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/core/task/KillServiceMock.scala
  src/test/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActorTest.scala
  src/test/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActorTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/MetricsIntegrationTest.scala
Labels: needs backport

#6607 Only log zero-value offers for scalar resources and ranges
  src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala
Labels: backport-1.7

#6608 Only log zero-value offers for scalar resources and ranges (#6595)
  src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala
Labels: backport-1.6

#6610 `TaskOverdueActor` now respects `--kill_retry_timeout` parameter (#6596)
  changelog.md
  docs/docs/metrics.md
  src/main/scala/mesosphere/marathon/MarathonSchedulerActor.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/TaskJobsModule.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/KillConfig.scala
  src/main/scala/mesosphere/marathon/core/task/termination/KillService.scala
  src/main/scala/mesosphere/marathon/core/task/termination/TaskTerminationModule.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceDelegate.scala
  src/test/scala/mesosphere/marathon/SchedulerActionsTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/instance/TestTaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/core/task/KillServiceMock.scala
  src/test/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActorTest.scala
  src/test/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActorTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/MetricsIntegrationTest.scala
Labels: backport-1.7, last one merges

#6611 `TaskOverdueActor` now respects `--kill_retry_timeout` parameter (#6596)
  changelog.md
  src/main/scala/mesosphere/marathon/MarathonSchedulerActor.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/TaskJobsModule.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/KillConfig.scala
  src/main/scala/mesosphere/marathon/core/task/termination/KillService.scala
  src/main/scala/mesosphere/marathon/core/task/termination/TaskTerminationModule.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceDelegate.scala
  src/test/scala/mesosphere/marathon/SchedulerActionsTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/instance/TestTaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/core/task/KillServiceMock.scala
  src/test/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActorTest.scala
Labels: backport-1.6, last one merges

#6613 `TaskOverdueActor` now respects `--kill_retry_timeout` parameter (#6596)
  changelog.md
  src/main/scala/mesosphere/marathon/MarathonSchedulerActor.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/TaskJobsModule.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/KillConfig.scala
  src/main/scala/mesosphere/marathon/core/task/termination/KillService.scala
  src/main/scala/mesosphere/marathon/core/task/termination/TaskTerminationModule.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceDelegate.scala
  src/test/scala/mesosphere/marathon/SchedulerActionsTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/instance/TestTaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/task/KillServiceMock.scala
  src/test/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActorTest.scala
Labels: backport-1.5, last one merges

#6591 Clean sbt integration test project. (#6584)
  ci/pipeline
Labels: backport-1.7

#6594 Fix for broken versioning of Apps and Pods (#6558)
  src/main/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStore.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/zk/ZkPersistenceStoreTest.scala
Labels: backport-1.5

#6620 Set other user read/exec perms for starthookfile
  tests/package/test.sc
Labels: needs backport

#6624 Set other user read/exec perms for starthookfile (#6620)
  tests/package/test.sc
Labels: backport-1.7

#6625 Set other user read/exec perms for starthookfile (#6620)
  tests/package/test.sc
Labels: backport-1.6

#6626 Set other user read/exec perms for starthookfile (#6620)
  tests/package/test.sc
Labels: backport-1.5
