Repository mesosphere/marathon, pull requests merged in 2018-06, with the labels that each got.

#6270 Properly return Content-Type header when using async proxy
  src/main/scala/mesosphere/marathon/api/forwarder/AsyncUrlConnectionRequestForwarder.scala
  src/main/scala/mesosphere/marathon/api/forwarder/RequestForwarder.scala
  tests/integration/src/test/scala/mesosphere/IntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/ForwardToLeaderIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/ForwarderService.scala
Labels: last one merges

#6274 Improved documentation about `max_running_deployments` parameter
  changelog.md
  src/main/scala/mesosphere/marathon/Exception.scala
Labels: last one merges

#6273 Backport stabilization fixes for MesosAppIntegrationTest
  src/test/scala/mesosphere/UnitTest.scala
  src/test/scala/mesosphere/marathon/integration/MesosAppIntegrationTest.scala
Labels: wip

#6272 Marathon 1.4.8 -> 1.5.8 - negative taskKillGracePeriodSeconds fix
  src/main/scala/mesosphere/marathon/raml/AppConversion.scala
Labels: needs backport

#6281 When proxying events, flush after each element received
  src/main/scala/mesosphere/marathon/api/forwarder/ServletOutputStreamSink.scala
Labels: last one merges

#6282 Backport `AppDeployIntegrationTest` fixes
  src/test/scala/mesosphere/marathon/integration/AppDeployIntegrationTest.scala
Labels: last one merges

#6275 Marathon 1.4.8 -> 1.5.8 - negative taskKillGracePeriodSeconds fix
  src/main/scala/mesosphere/marathon/raml/AppConversion.scala
Labels: backport-1.5

#6301 Reschedule resident task during a deployment
  src/main/scala/mesosphere/marathon/core/deployment/impl/StartingBehavior.scala
  src/main/scala/mesosphere/marathon/core/instance/Instance.scala
  src/main/scala/mesosphere/marathon/core/task/Task.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegate.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/TaskStartActorTest.scala
  src/test/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegateTest.scala
Labels: needs backport

#6306 Warn if any resource in an incoming offer is set to zero
  src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala
Labels: needs backport

#6305 Introduce `bytesWritten` counter for the events endpoint
  src/main/scala/mesosphere/marathon/core/event/impl/stream/HttpEventStreamServlet.scala
Labels: small and cute

#6322 Warn if any resource in an incoming offer is set to zero (#6306)
  src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala
Labels: backport-1.5
