Repository mesosphere/marathon, pull requests merged in 2018-03, with the labels that each got.

#6051 Implement gpu_scheduling_behavior parameter and basic functionality
  docs/docs/rest-api/public/api/v2/examples/queue.json
  src/main/scala/mesosphere/marathon/GpuSchedulingBehavior.scala
  src/main/scala/mesosphere/marathon/MarathonConf.scala
  src/main/scala/mesosphere/marathon/core/launcher/impl/InstanceOpFactoryImpl.scala
  src/main/scala/mesosphere/mesos/MatcherConf.scala
  src/main/scala/mesosphere/mesos/NoOfferMatchReason.scala
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/QueueControllerTest.scala
  src/test/scala/mesosphere/marathon/api/v2/QueueResourceTest.scala
  src/test/scala/mesosphere/marathon/raml/QueueInfoConversionTest.scala
  src/test/scala/mesosphere/marathon/test/MarathonTestHelper.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
Labels: fluffy

#6057 Open the persistence store before taking a backup using CLI
  src/main/scala/mesosphere/marathon/core/storage/backup/Backup.scala
Labels: backport-1.5

#6063 Fixed a broken link in the event bus documentation page
  docs/docs/event-bus.md
Labels: documentation

#6061 Integration tests for Preferential GPU Scheduling in Marathon
  src/test/scala/mesosphere/marathon/integration/GpuSchedulingIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/setup/MarathonTest.scala
  src/test/scala/mesosphere/marathon/integration/setup/MesosTest.scala
Labels: small and cute

#6054 Do not start more instances than needed
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/TaskLauncherActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegate.scala
  src/test/scala/mesosphere/marathon/integration/AppDeployIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/EventsIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/GracefulTaskKillIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/GroupDeployIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/MesosAppIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/ReadinessCheckIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/ResidentTaskIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/SystemResourceIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/facades/MarathonFacade.scala
  src/test/scala/mesosphere/marathon/integration/setup/MarathonTest.scala
Labels: backport-1.5

#6066 Document how to configure log rotation in docker containers
  docs/docs/native-docker.md
Labels: documentation

#6064 Describe the usage of LIBPROCESS_PORT in the troubleshooting section
  docs/docs/troubleshooting.md
Labels: documentation

#6074 Drop Akka-http controllers
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/AkkaHttpMarathonService.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/AkkaHttpModule.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/AppsDirectives.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/AuthDirectives.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/Controller.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/Directives.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/EntityMarshallers.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/Headers.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/HttpPluginFacade.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/LeaderDirectives.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/PathMatchers.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/Rejections.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/ResourceController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/SystemController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/V2Controller.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/AppsController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/EventsController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/GroupsController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/InfoController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/LeaderController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/PluginsController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/PodsController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/QueueController.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/TasksController.scala
  src/test/scala/mesosphere/ValidationTestLike.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/AppsDirectivesTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/PathMatchersTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/SystemControllerTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/AppsControllerTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/EventsControllerTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/GroupsControllerTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/InfoControllerTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/LeaderControllerTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/PodsControllerTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/QueueControllerTest.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/ResponseMatchers.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/RouteBehaviours.scala
  src/test/scala/mesosphere/marathon/api/akkahttp/v2/TasksControllerTest.scala
Labels: fluffy, spring-cleaning

#6072 Always unreserve resources for non-existing instances
  src/main/scala/mesosphere/marathon/core/launcher/InstanceOp.scala
  src/test/scala/mesosphere/marathon/core/launcher/InstanceOpTest.scala
Labels: backport-1.5

#6073 Always unreserve resources for non-existing instances
  src/main/scala/mesosphere/marathon/core/launcher/InstanceOp.scala
  src/test/scala/mesosphere/marathon/core/launcher/InstanceOpTest.scala
Labels: backport-1.4

#6075 Consolidate tools.
  README.md
  bin/run-tests-config-template.sh
  bin/run-tests-in-loop.sh
  bin/run-tests.sh
  docs/docs/contributing.md
  scripts/mark_unstable_results.sc
  scripts/publish_packages.sh
  tools/mvm.sh
Labels: spring-cleaning

#6079 Remove examples folder
  docs/docs/service-discovery-load-balancing.md
  examples/Group-1.json
  examples/Group-2.json
  examples/Play.json
  examples/PythonSimpleHTTPServer.json
  examples/README.md
  examples/Rails.json
  examples/Tomcat-Docker.json
  examples/Tomcat.json
  examples/bridge.json
  examples/haproxy-marathon-bridge
  examples/labels.json
Labels: spring-cleaning

#6077 Removed old python scale tests
  Jenkinsfile.scale
  tests/scale/README.md
  tests/scale/common.py
  tests/scale/example/meta-data.json
  tests/scale/example/scale-test.csv
  tests/scale/example/scale.png
  tests/scale/graph.py
  tests/scale/mom.json
  tests/scale/over-provision.py
  tests/scale/over-provision.sh
  tests/scale/pod-2-containers.json
  tests/scale/pod-4-containers.json
  tests/scale/test_marathon_cap.py
  tests/scale/test_mom_pod_scale.py
  tests/scale/test_root_marathon_scale.py
  tests/scale/utils.py
Labels: spring-cleaning

#6082 Forward docs port from 1.5 to master
  docs/_layouts/default.html
  docs/_layouts/docs.html
  docs/docs/application-basics.md
  docs/docs/command-line-flags.md
  docs/docs/event-bus.md
  docs/docs/marathon-ui.md
  docs/docs/native-docker-private-registry.md
  docs/docs/recipes.md
  docs/docs/rest-api/public/api/v2/apps.raml
  docs/index.md
Labels: documentation

#6090 Add support for symlinks for `--plugin_dir` and `--plugin_conf` parameters
  src/main/scala/mesosphere/marathon/core/plugin/impl/PluginManagerImpl.scala
  src/main/scala/mesosphere/marathon/io/IO.scala
Labels: needs backport, small and cute

#6092 Add support for symlinks for `--plugin_dir` and `--plugin_conf` parameters
  src/main/scala/mesosphere/marathon/core/plugin/impl/PluginManagerImpl.scala
  src/main/scala/mesosphere/marathon/io/IO.scala
Labels: backport-1.5, last one merges

#6087 Do not start more instances than needed
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/TaskLauncherActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegate.scala
  src/test/scala/mesosphere/marathon/integration/MarathonStartupIntegrationTest.scala
Labels: backport-1.4

#6098 Disable Connection Pooling for HTTP Health Checks
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerActor.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerActorTest.scala
Labels: backport-1.5

#6078 Backport: Implement gpu_scheduling_behavior parameter and basic functionality
  docs/docs/rest-api/public/api/v2/examples/queue.json
  src/main/scala/mesosphere/marathon/GpuSchedulingBehavior.scala
  src/main/scala/mesosphere/marathon/MarathonConf.scala
  src/main/scala/mesosphere/marathon/core/launcher/impl/InstanceOpFactoryImpl.scala
  src/main/scala/mesosphere/mesos/NoOfferMatchReason.scala
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/main/scala/mesosphere/mesos/RunSpecOfferMatcher.scala
  src/test/scala/mesosphere/marathon/api/v2/QueueResourceTest.scala
  src/test/scala/mesosphere/marathon/core/health/MesosHealthCheckTest.scala
  src/test/scala/mesosphere/marathon/raml/QueueInfoConversionTest.scala
  src/test/scala/mesosphere/marathon/test/MarathonTestHelper.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
  src/test/scala/mesosphere/mesos/TaskBuilderTest.scala
  src/test/scala/mesosphere/mesos/TaskGroupBuilderTest.scala
Labels: backport-1.5

#6107 Integration tests for Preferential GPU Scheduling in Marathon
  src/test/scala/mesosphere/marathon/integration/GpuSchedulingIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/setup/MarathonTest.scala
  src/test/scala/mesosphere/marathon/integration/setup/MesosTest.scala
Labels: backport-1.5

#6105 Stabilize `MesosAppIntegrationTest`
  src/test/scala/mesosphere/marathon/integration/DockerAppIntegrationTest.scala
  src/test/scala/mesosphere/marathon/integration/MesosAppIntegrationTest.scala
Labels: last one merges, small and cute

#6118 Fail build pipeline if leaked process exist after integration tests
  ci/pipeline
  ci/provision.sc
Labels: small and cute

#6100 SystemConfig is the Correct Security Constraint
  src/main/scala/mesosphere/marathon/api/SystemResource.scala
Labels: backport

#6124 Backport #6121 to 1.5.x
  src/main/scala/mesosphere/marathon/Main.scala
Labels: backport-1.5
