Repository mesosphere/marathon, pull requests merged in 2018-05, with the labels that each got.

#6185 Replace LoggingFactory with StrictLogging pt. 2
  mesos-simulation/src/main/scala/mesosphere/mesos/simulation/DriverActor.scala
  mesos-simulation/src/main/scala/mesosphere/mesos/simulation/SchedulerActor.scala
  mesos-simulation/src/main/scala/mesosphere/mesos/simulation/SimulatedDriver.scala
  mesos-simulation/src/test/scala/mesosphere/mesos/scale/SingleAppScalingTest.scala
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/MarathonModule.scala
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerDriver.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
  src/main/scala/mesosphere/marathon/SchedulerDriverFactory.scala
  src/main/scala/mesosphere/marathon/api/MarathonExceptionMapper.scala
  src/main/scala/mesosphere/marathon/api/WebJarServlet.scala
  src/main/scala/mesosphere/marathon/api/v2/AppTasksResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppVersionsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/InfoEmbedResolver.scala
  src/main/scala/mesosphere/marathon/api/v2/LabelSelector.scala
  src/main/scala/mesosphere/marathon/api/v2/TasksResource.scala
  src/main/scala/mesosphere/marathon/api/v2/Validation.scala
  src/main/scala/mesosphere/marathon/core/deployment/impl/DeploymentPlanReverter.scala
  src/main/scala/mesosphere/marathon/core/deployment/impl/ReadinessBehavior.scala
  src/main/scala/mesosphere/marathon/core/event/EventModule.scala
  src/main/scala/mesosphere/marathon/core/event/impl/stream/HttpEventStreamActor.scala
  src/main/scala/mesosphere/marathon/core/flow/FlowModule.scala
  src/main/scala/mesosphere/marathon/core/health/HealthCheckManager.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerActor.scala
  src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala
  src/main/scala/mesosphere/marathon/core/heartbeat/HeartbeatActor.scala
  src/main/scala/mesosphere/marathon/core/heartbeat/MesosHeartbeatMonitor.scala
  src/main/scala/mesosphere/marathon/core/launcher/impl/InstanceOpFactoryImpl.scala
  src/main/scala/mesosphere/marathon/core/launcher/impl/TaskLauncherImpl.scala
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/RateLimiter.scala
  src/main/scala/mesosphere/marathon/core/readiness/impl/ReadinessCheckExecutorImpl.scala
  src/main/scala/mesosphere/marathon/core/task/Task.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/impl/OverdueTasksActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceUpdateActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstancesLoaderImpl.scala
  src/main/scala/mesosphere/marathon/core/task/update/impl/steps/PostToEventStreamStepImpl.scala
  src/main/scala/mesosphere/marathon/core/task/update/impl/steps/ScaleAppUpdateStepImpl.scala
  src/main/scala/mesosphere/marathon/metrics/SlidingAverageSnapshot.scala
  src/main/scala/mesosphere/marathon/tasks/ResourceUtil.scala
  src/main/scala/mesosphere/marathon/upgrade/GroupVersioningUtil.scala
  src/main/scala/mesosphere/mesos/Constraints.scala
  src/test/scala/mesosphere/marathon/core/instance/TestTaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/task/bus/TaskStatusUpdateTestHelper.scala
  src/test/scala/mesosphere/marathon/integration/setup/ProcessOutputToLogStream.scala
Labels: last one merges

#6186 Limit max number of concurrently running deployments (#6178)
  changelog.md
  docs/docs/command-line-flags.md
  src/main/scala/mesosphere/marathon/Exception.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
  src/main/scala/mesosphere/marathon/api/MarathonExceptionMapper.scala
  src/main/scala/mesosphere/marathon/core/group/GroupManagerConfig.scala
  src/main/scala/mesosphere/marathon/core/group/impl/GroupManagerImpl.scala
  src/main/scala/mesosphere/marathon/core/health/impl/AppHealthCheckActor.scala
  src/test/scala/mesosphere/marathon/api/TestGroupManagerFixture.scala
  src/test/scala/mesosphere/marathon/api/v2/GroupsResourceTest.scala
  src/test/scala/mesosphere/marathon/core/group/GroupManagerTest.scala
Labels: backport-1.5

#6198 Fix the behaviour of the GcActor in marathon
  src/main/scala/mesosphere/marathon/state/Group.scala
  src/main/scala/mesosphere/marathon/storage/StorageConf.scala
  src/main/scala/mesosphere/marathon/storage/StorageConfig.scala
  src/main/scala/mesosphere/marathon/storage/StorageModule.scala
  src/main/scala/mesosphere/marathon/storage/repository/DeploymentRepositoryImpl.scala
  src/main/scala/mesosphere/marathon/storage/repository/GcActor.scala
  src/main/scala/mesosphere/marathon/storage/repository/Repositories.scala
  src/test/scala/mesosphere/marathon/storage/migration/MigrationTest.scala
  src/test/scala/mesosphere/marathon/storage/repository/GcActorTest.scala
Labels: fluffy, needs backport

#6217 Fix master loop failure metric
  ci/pipeline
Labels: last one merges

#6214 Switch to Scalatest JUnitXMLReporter to regain the timestamp field
  Jenkinsfile
  build.sbt
Labels: needs backport

#6216 Pod failure reasons are not visible in the UI/API
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/api/akkahttp/v2/AppsController.scala
  src/main/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseData.scala
  src/main/scala/mesosphere/marathon/core/deployment/DeploymentModule.scala
  src/main/scala/mesosphere/marathon/core/event/Events.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerActor.scala
  src/main/scala/mesosphere/marathon/metrics/Metrics.scala
  src/test/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseDataTest.scala
  src/test/scala/mesosphere/marathon/state/TaskFailureTest.scala
  src/test/scala/mesosphere/marathon/state/TaskFailureTestHelper.scala
Labels: backport-1.5

#6224 Adding launchOperations, launchGroupOperations, reserveOperations
  src/main/scala/mesosphere/marathon/core/matcher/base/util/OfferOperationFactory.scala
Labels: needs tests

#6228 Adding launchOperations, launchGroupOperations, reserveOperations
  src/main/scala/mesosphere/marathon/core/matcher/base/util/OfferOperationFactory.scala
Labels: backport-1.5

#6227 Introduce task metrics
  src/main/scala/mesosphere/marathon/metrics/AtomicGauge.scala
Labels: needs backport, needs tests

#6235 Fix Mesos HTTP health check for non-host networking mode with `containerPort=0`
  src/main/scala/mesosphere/marathon/core/health/HealthCheck.scala
  src/main/scala/mesosphere/marathon/core/task/state/NetworkInfo.scala
  src/main/scala/mesosphere/mesos/EnvironmentHelper.scala
  src/main/scala/mesosphere/mesos/TaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/health/MesosHealthCheckTest.scala
  src/test/scala/mesosphere/marathon/core/task/state/NetworkInfoTest.scala
Labels: needs backport

#6240 Fix Mesos HTTP health check for non-host networking mode with `containerPort=0` (#6235)
  src/main/scala/mesosphere/marathon/core/health/HealthCheck.scala
  src/main/scala/mesosphere/marathon/core/task/state/NetworkInfo.scala
  src/main/scala/mesosphere/mesos/EnvironmentHelper.scala
  src/main/scala/mesosphere/mesos/TaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/health/MesosHealthCheckTest.scala
  src/test/scala/mesosphere/marathon/core/task/state/NetworkInfoTest.scala
Labels: backport-1.5, last one merges

#6242 Update extra-defines.bash
  project/NativePackagerSettings/extra-defines.bash
Labels: backport-1.5, needs backport

#6250 Add a note for service name length
  docs/docs/application-basics.md
  docs/docs/pods.md
  docs/docs/service-discovery-load-balancing.md
Labels: needs backport

#6252 Add a note for service name length (#6250)
  docs/docs/application-basics.md
  docs/docs/pods.md
  docs/docs/service-discovery-load-balancing.md
Labels: backport-1.5

#6258 Fix ZK layout migration when store caching is disabled
  src/main/scala/mesosphere/marathon/storage/migration/MigrationTo15.scala
Labels: backport-1.5
