Repository mesosphere/marathon, pull requests merged in 2018-11, with the labels that each got.

#6637 Allow Docker image tests to run without building native packages
  tests/package/test.sc
Labels: last one merges

#6649 Fixed a precision bug when sum-ing doubles
  src/main/scala/mesosphere/marathon/core/pod/PodDefinition.scala
  src/test/scala/mesosphere/marathon/core/pod/PodDefinitionTest.scala
Labels: backport-1.5

#6648 Fixed a precision bug when sum-ing doubles
  src/main/scala/mesosphere/marathon/core/pod/PodDefinition.scala
  src/test/scala/mesosphere/marathon/core/pod/PodDefinitionTest.scala
Labels: backport-1.6

#6647 Fixed a precision bug when sum-ing doubles
  src/main/scala/mesosphere/marathon/core/pod/PodDefinition.scala
  src/test/scala/mesosphere/marathon/core/pod/PodDefinitionTest.scala
Labels: backport-1.7

#6598 Remove `InstanceUpdateActor`.
  src/main/scala/mesosphere/marathon/core/deployment/impl/TaskReplaceActor.scala
  src/main/scala/mesosphere/marathon/core/instance/update/InstanceUpdateOpResolver.scala
  src/main/scala/mesosphere/marathon/core/instance/update/InstanceUpdateOperation.scala
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueActor.scala
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/TaskLauncherActor.scala
  src/main/scala/mesosphere/marathon/core/matcher/manager/impl/OfferMatcherManagerActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/InstanceTrackerConfig.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/InstanceTrackerModule.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegate.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceUpdateActor.scala
  src/test/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseDataTest.scala
  src/test/scala/mesosphere/marathon/core/instance/update/InstanceUpdateOpResolverTest.scala
  src/test/scala/mesosphere/marathon/core/task/bus/TaskStatusUpdateTestHelper.scala
  src/test/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerActorTest.scala
  src/test/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegateTest.scala
  src/test/scala/mesosphere/marathon/core/task/tracker/impl/InstanceUpdateActorTest.scala
  src/test/scala/mesosphere/marathon/tasks/InstanceTrackerImplTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/GroupDeployIntegrationTest.scala
Labels: fluffy

#6670 Fix for a secrets validator error when we change env without changing secrets (#6651)
  src/main/scala/mesosphere/marathon/Normalization.scala
  src/main/scala/mesosphere/marathon/api/v2/AppHelpers.scala
  src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/validation/AppValidation.scala
  src/test/scala/mesosphere/marathon/api/v2/AppsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/json/AppDefinitionFormatsTest.scala
  src/test/scala/mesosphere/marathon/api/v2/json/AppUpdateFormatTest.scala
  src/test/scala/mesosphere/marathon/api/v2/json/AppUpdateTest.scala
  src/test/scala/mesosphere/marathon/api/v2/validation/AppValidationTest.scala
  src/test/scala/mesosphere/marathon/api/validation/AppUpdateValidatorTest.scala
Labels: backport-1.6

#6669 Fix for a secrets validator error when we change env without changing…
  src/main/scala/mesosphere/marathon/Normalization.scala
  src/main/scala/mesosphere/marathon/api/v2/AppHelpers.scala
  src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/validation/AppValidation.scala
  src/test/scala/mesosphere/marathon/api/v2/AppsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/json/AppDefinitionFormatsTest.scala
  src/test/scala/mesosphere/marathon/api/v2/json/AppUpdateFormatTest.scala
  src/test/scala/mesosphere/marathon/api/v2/json/AppUpdateTest.scala
  src/test/scala/mesosphere/marathon/api/v2/validation/AppValidationTest.scala
  src/test/scala/mesosphere/marathon/api/validation/AppUpdateValidatorTest.scala
Labels: backport-1.7
