Repository mesosphere/marathon, pull requests merged in 2018-09, with the labels that each got.

#6497 Document new exit codes in changelog. (#6486)
  changelog.md
Labels: backport-1.6

#6504 Marathon UI 1.3.1 in Marathon 1.4
  changelog.md
  project/Dependencies.scala
Labels: backport-1.4

#6503 Marathon UI 1.3.1 in Marathon 1.5
  changelog.md
  project/Dependencies.scala
Labels: backport-1.5

#6502 Marathon UI 1.3.1 in Marathon 1.6
  changelog.md
  project/Dependencies.scala
Labels: backport-1.6

#6513 Add logging to the `GroupManagerImpl`
  src/main/scala/mesosphere/marathon/core/group/impl/GroupManagerImpl.scala
Labels: yolo

#6475 PATCH call not proxied correctly to active node
  src/main/scala/mesosphere/marathon/api/forwarder/JavaUrlConnectionRequestForwarder.scala
Labels: needs backport

#6506 Fix of flaky behavior in TaskUnreachableIntegrationTest.
  tests/integration/src/test/scala/mesosphere/marathon/integration/TaskUnreachableIntegrationTest.scala
Labels: wip

#6522 Backport 1.6: PATCH call not proxied correctly to active node (#6475)
  src/main/scala/mesosphere/marathon/api/forwarder/JavaUrlConnectionRequestForwarder.scala
Labels: backport-1.6

#6523 Update `dcos-test-utils` dependency to latest master
  tests/system/Pipfile
  tests/system/Pipfile.lock
Labels: yolo

#6476 PATCH call not proxied correctly to active node
  src/main/scala/mesosphere/marathon/api/LeaderProxyFilter.scala
Labels: backport-1.5

#6514 Detect and better handle zk connection turbulence with CuratorElectionStream
  src/main/scala/mesosphere/marathon/core/election/CuratorElectionStream.scala
  tests/integration/src/test/scala/mesosphere/marathon/core/election/CuratorElectionStreamTest.scala
Labels: needs backport

#6527 Populate PodStatus startedAt with instance timestamp
  src/main/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseData.scala
Labels: fluffy, last one merges, needs backport

#6531 Populate PodStatus startedAt with instance timestamp (#6527)
  src/main/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseData.scala
Labels: backport-1.6

#6532 Populate PodStatus startedAt with instance timestamp (#6527)
  src/main/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseData.scala
Labels: backport-1.5

#6539 Remove fpm-docker provision file.
  .gitignore
  tools/packager/fpm-docker/.provisioned
Labels: yolo

#6536 HTTPS readiness checks do not check certificates
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerActor.scala
  src/main/scala/mesosphere/marathon/core/readiness/impl/ReadinessCheckExecutorImpl.scala
Labels: needs backport

#6541 HTTPS readiness checks do not check certificates
  src/main/scala/mesosphere/marathon/api/LeaderProxyFilter.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerActor.scala
  src/main/scala/mesosphere/marathon/core/readiness/impl/ReadinessCheckExecutorImpl.scala
Labels: backport-1.5

#6540 HTTPS readiness checks do not check certificates
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerActor.scala
  src/main/scala/mesosphere/marathon/core/readiness/impl/ReadinessCheckExecutorImpl.scala
Labels: backport-1.6

#6564 Fix references to shorthand key
  ami/install.bash
  build.sbt
  docs/docs/native-packages.md
  tests/jepsen/src/jepsen/mesos.clj
  tests/package/debian-systemd/Dockerfile
  tests/package/ubuntu-upstart/Dockerfile
Labels: backport-1.5

#6563 Fix references to shorthand key
  ami/install.bash
  build.sbt
  docs/docs/native-packages.md
  tests/jepsen/src/jepsen/mesos.clj
  tests/package/debian-systemd/Dockerfile
  tests/package/ubuntu-upstart/Dockerfile
Labels: backport-1.6

#6568 Increase http proxy max-open-connections values; configure via flag
  changelog.md
  docs/docs/command-line-flags.md
  src/main/scala/mesosphere/marathon/DeprecatedFeatures.scala
  src/main/scala/mesosphere/marathon/LeaderProxyConf.scala
  src/main/scala/mesosphere/marathon/api/forwarder/AsyncUrlConnectionRequestForwarder.scala
Labels: backport-1.6
