Repository mesosphere/marathon, pull requests merged in 2018-07, with the labels that each got.

#6313 Properly handle ENV args containing "*", " ", or line delimiters
  changelog.md
  project/NativePackagerSettings/extra-defines.bash
  src/main/scala/mesosphere/marathon/Main.scala
  src/test/scala/mesosphere/marathon/MainTest.scala
Labels: needs backport

#6335 Move the instance update to the update method
  src/main/scala/mesosphere/marathon/core/instance/update/InstanceUpdater.scala
  src/test/scala/mesosphere/marathon/core/instance/TestInstanceBuilder.scala
Labels: last one merges

#6347 Activate `HeartbeatMonitor` even before Marathon is connected to Mesos
  src/main/scala/mesosphere/marathon/MarathonModule.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
  src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala
  src/main/scala/mesosphere/marathon/core/heartbeat/HeartbeatActor.scala
  src/main/scala/mesosphere/marathon/core/heartbeat/MesosHeartbeatMonitor.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala
  src/test/scala/mesosphere/marathon/core/heartbeat/HeartbeatActorTest.scala
  src/test/scala/mesosphere/marathon/core/heartbeat/MesosHeartbeatMonitorTest.scala
Labels: needs backport

#6351 Introduce option to suppress offers
  docs/docs/command-line-flags.md
  src/main/scala/mesosphere/marathon/core/flow/ReviveOffersConfig.scala
  src/main/scala/mesosphere/marathon/core/flow/impl/ReviveOffersActor.scala
  src/test/scala/mesosphere/marathon/core/flow/impl/ReviveOffersActorTest.scala
Labels: backport-1.5, backport-1.6, last one merges, needs backport

#6355 Activate `HeartbeatMonitor` even before Marathon is connected to Mesos (#6347)
  src/main/scala/mesosphere/marathon/MarathonModule.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
  src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala
  src/main/scala/mesosphere/marathon/core/heartbeat/HeartbeatActor.scala
  src/main/scala/mesosphere/marathon/core/heartbeat/MesosHeartbeatMonitor.scala
  src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala
  src/test/scala/mesosphere/marathon/core/heartbeat/HeartbeatActorTest.scala
  src/test/scala/mesosphere/marathon/core/heartbeat/MesosHeartbeatMonitorTest.scala
Labels: backport-1.5

#6353 Activate `HeartbeatMonitor` even before Marathon is connected to Mesos (#6347)
  src/main/scala/mesosphere/marathon/MarathonModule.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
  src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala
  src/main/scala/mesosphere/marathon/core/heartbeat/HeartbeatActor.scala
  src/main/scala/mesosphere/marathon/core/heartbeat/MesosHeartbeatMonitor.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala
  src/test/scala/mesosphere/marathon/core/heartbeat/HeartbeatActorTest.scala
  src/test/scala/mesosphere/marathon/core/heartbeat/MesosHeartbeatMonitorTest.scala
Labels: backport-1.6

#6354 Backport fix for flaky `SlidingAverageSnapshotTest`
  src/main/scala/mesosphere/marathon/metrics/SlidingAverageSnapshot.scala
Labels: backport-1.6

#6376 Try to fix races in resident relaunching
  src/main/scala/mesosphere/marathon/core/instance/update/InstanceUpdateOpResolver.scala
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueActor.scala
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/TaskLauncherActor.scala
Labels: wip

#6226 Group versions cache size config validation
  src/main/scala/mesosphere/marathon/MarathonConf.scala
  src/main/scala/mesosphere/marathon/storage/StorageConf.scala
  src/main/scala/mesosphere/marathon/storage/StorageConfig.scala
  src/main/scala/mesosphere/marathon/storage/StorageModule.scala
  src/main/scala/mesosphere/marathon/storage/repository/GroupRepositoryImpl.scala
  src/main/scala/mesosphere/marathon/storage/repository/Repositories.scala
  src/test/scala/mesosphere/marathon/storage/migration/MigrationTest.scala
  src/test/scala/mesosphere/marathon/storage/repository/GcActorTest.scala
  src/test/scala/mesosphere/marathon/storage/repository/GroupRepositoryTest.scala
  tools/elk/bin/target
Labels: wip

#6385 Documentation page for native packages
  changelog.md
  ci/releases.sc
  docs/docs/index.md
  docs/docs/native-packages.md
Labels: backport-1.5, backport-1.6

#6389 Documentation page for native packages
  changelog.md
  ci/releases.sc
  docs/docs/index.md
  docs/docs/native-packages.md
Labels: backport-1.6

#6390 Documentation page for native packages
  changelog.md
  ci/pipeline
  docs/docs/index.md
  docs/docs/native-packages.md
Labels: backport-1.5

#6334 Log incoming offers at info level
  src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala
Labels: backport-1.5, small and cute
