Repository mesosphere/marathon, pull requests merged in 2018-02, with the labels that each got.

#6001 Optimize `v2/groups` request performance
  src/main/scala/mesosphere/marathon/MarathonConf.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerServiceConfig.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/appinfo/AppInfoConfig.scala
  src/main/scala/mesosphere/marathon/core/appinfo/AppInfoModule.scala
  src/main/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseData.scala
  src/main/scala/mesosphere/marathon/core/appinfo/impl/DefaultInfoService.scala
  src/main/scala/mesosphere/marathon/core/group/GroupManagerConfig.scala
  src/main/scala/mesosphere/marathon/storage/StorageConf.scala
  src/main/scala/mesosphere/util/ThreadPoolContext.scala
  src/test/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseDataTest.scala
  src/test/scala/mesosphere/marathon/core/appinfo/impl/DefaultInfoServiceTest.scala
Labels: backport-1.5

#5995 Changelog note about scala 2.12
  changelog.md
Labels: small and cute

#6004 Fixed some additional compile warning
  src/test/scala/mesosphere/marathon/LaunchQueueModuleTest.scala
  src/test/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseDataTest.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/DeploymentActorTest.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/DeploymentManagerActorTest.scala
  src/test/scala/mesosphere/marathon/core/storage/store/impl/cache/LazyCachingPersistenceStoreTest.scala
  src/test/scala/mesosphere/marathon/core/task/tracker/impl/InstanceOpProcessorImplTest.scala
  src/test/scala/mesosphere/marathon/integration/RemoteRegionOffersIntegrationTest.scala
Labels: last one merges, small and cute

#6007 IS constraint in the validation message
  src/main/scala/mesosphere/marathon/api/v2/validation/SchedulingValidation.scala
Labels: last one merges, small and cute

#6012 Fix the link in plugin docs
  docs/docs/plugin.md
Labels: last one merges

#6009 Update docs with valid examples for fetch URIs
  docs/docs/application-basics.md
  docs/docs/event-bus.md
  docs/docs/marathon-ui.md
  docs/docs/native-docker-private-registry.md
  docs/docs/recipes.md
  examples/Play.json
  examples/Rails.json
  examples/Tomcat.json
Labels: documentation

#6014 Using stretch-slim as the new upstream for the docker image
  build.sbt
  project/Dependencies.scala
Labels: small and cute

#6015 Add support for Graphite reporter interval parameter
  docs/docs/command-line-flags.md
  src/main/scala/mesosphere/marathon/Main.scala
Labels: backport-1.5

#6021 documentation: Fix broken link format
  docs/docs/native-docker-private-registry.md
Labels: community

#6016 1.4 Backport: Update docs with valid examples for fetch URIs
  docs/docs/application-basics.md
  docs/docs/event-bus.md
  docs/docs/marathon-ui.md
  docs/docs/native-docker-private-registry.md
  docs/docs/recipes.md
  examples/Play.json
  examples/Rails.json
  examples/Tomcat.json
Labels: backport-1.4, documentation

#5974 Script for generating versioned documentation for marathon
  ci/generate_docs.sc
  ci/utils.sc
  docs/Dockerfile
  docs/entrypoint.sh
  project/Dependencies.scala
Labels: small and cute

#6031 Backport to 1.3: Document mesos role config limitations in Marathon
  docs/docs/command-line-flags.md
Labels: backport, documentation

#6037 Update docs for PATCH mode
  docs/docs/rest-api/public/api/v2/apps.raml
Labels: documentation, needs backport, small and cute

#6036 Update the instructions for docs generation
  ci/generate_docs.sc
  docs/README.md
Labels: documentation, small and cute
