Repository mesosphere/marathon, pull requests merged in 2018-12, with the labels that each got.

#6706 Use distinct exist code for the incompatible LibMesos version
  docs/docs/exit-codes.md
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
  src/main/scala/mesosphere/mesos/LibMesos.scala
Labels: last one merges

#6712 adjust minor versions in dcos versions script
  tools/dcos-versions.sc
Labels: fluffy

#6705 Do not lock when doing kill from API
  src/main/scala/mesosphere/marathon/MarathonSchedulerActor.scala
  src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
  src/main/scala/mesosphere/marathon/api/TaskKiller.scala
  src/main/scala/mesosphere/marathon/core/deployment/impl/StartingBehavior.scala
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/TaskLauncherActor.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerActorTest.scala
  src/test/scala/mesosphere/marathon/api/TaskKillerTest.scala
  src/test/scala/mesosphere/marathon/api/v2/SpecInstancesResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/TasksResourceTest.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/TaskStartActorTest.scala
Labels: hold merge

#6713 Add folder and index for docs articles.
  docs/articles/README.md
  docs/articles/index.md
Labels: documentation, fluffy

#6720 Prohibit usage of reserved keywords as parts of path ids (#6632)
  changelog.md
  src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala
  src/main/scala/mesosphere/marathon/state/PathId.scala
  src/test/scala/mesosphere/marathon/state/PathIdTest.scala
Labels: backport-1.6

#6719 Prohibit usage of reserved keywords as parts of path ids (#6632)
  changelog.md
  src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala
  src/main/scala/mesosphere/marathon/state/PathId.scala
  src/test/scala/mesosphere/marathon/state/PathIdTest.scala
Labels: backport-1.5

#6750 Respond back with Mesos Source field exactly as we've received it
  project/Dependencies.scala
  src/main/scala/mesosphere/marathon/state/Volume.scala
  src/test/scala/mesosphere/marathon/state/VolumeTest.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
Labels: backport-1.7
