Repository mesosphere/marathon, pull requests merged in 2019-09, with the labels that each got.

#7051 [1.8] Trigger overdue reservations event not only for scheduled instances
  src/main/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActor.scala
Labels: backport-1.8, last one merges

#7054 Trigger correct downstream build for EE.
  Jenkinsfile
Labels: yolo

#7070 Add 'target' path element, packages are now built there
  tests/package/test.sc
Labels: backport-1.7

#7071 Remove Ubuntu 1404 package tests
  tests/package/Makefile
  tests/package/test.sc
  tests/package/ubuntu1404/Dockerfile
Labels: needs backport

#7065 Move package upload logic to packages makefile
  ci/pipeline
  ci/releases.sc
  tests/package/Makefile
  tests/package/test.sc
  tests/package/ubuntu1404/Dockerfile
  tools/packager/Makefile
  tools/packager/README.md
  tools/packager/bin/upload-package
  version
Labels: backport-1.8

#7073 Remove Ubuntu 1404 package tests (#7071)
  tests/package/Makefile
  tests/package/test.sc
  tests/package/ubuntu1404/Dockerfile
Labels: backport-1.7

#7076 Restrict task status message length to something managable for ZK
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerTest.scala
Labels: needs backport

#7077 Restrict task status message length to something managable for ZK
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerTest.scala
Labels: backport-1.8

#7078 Restrict task status message length to something managable for ZK
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/test/scala/mesosphere/marathon/MarathonSchedulerTest.scala
Labels: backport-1.7
