Repository mesosphere/marathon, pull requests merged in 2019-02, with the labels that each got.

#6786 Speed up `v2/pods/::status`
  src/main/scala/mesosphere/marathon/api/v2/PodsResource.scala
  src/main/scala/mesosphere/marathon/core/appinfo/PodStatusService.scala
  src/main/scala/mesosphere/marathon/core/appinfo/impl/DefaultInfoService.scala
  src/test/scala/mesosphere/marathon/api/v2/PodsResourceTest.scala
Labels: needs backport

#6790 Speed up `v2/pods/::status` (#6786)
  src/main/scala/mesosphere/marathon/api/v2/PodsResource.scala
  src/main/scala/mesosphere/marathon/core/appinfo/PodStatusService.scala
  src/main/scala/mesosphere/marathon/core/appinfo/impl/DefaultInfoService.scala
  src/test/scala/mesosphere/marathon/api/v2/PodsResourceTest.scala
Labels: backport-1.7

#6791 Speed up `v2/pods/::status` (#6786)
  src/main/scala/mesosphere/marathon/api/v2/PodsResource.scala
  src/main/scala/mesosphere/marathon/core/appinfo/PodStatusService.scala
  src/main/scala/mesosphere/marathon/core/appinfo/impl/DefaultInfoService.scala
  src/test/scala/mesosphere/marathon/api/v2/PodsResourceTest.scala
Labels: backport-1.6

#6793 Response asynchronously for all endpoints.
  src/main/scala/mesosphere/marathon/api/AuthResource.scala
  src/main/scala/mesosphere/marathon/api/RestResource.scala
  src/main/scala/mesosphere/marathon/api/SystemResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppTasksResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppVersionsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/DeploymentsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/GroupsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/InfoResource.scala
  src/main/scala/mesosphere/marathon/api/v2/LeaderResource.scala
  src/main/scala/mesosphere/marathon/api/v2/PluginsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/PodsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/QueueResource.scala
  src/main/scala/mesosphere/marathon/api/v2/TasksResource.scala
  src/test/scala/mesosphere/marathon/api/AuthResourceTest.scala
  src/test/scala/mesosphere/marathon/api/SystemResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/AppVersionsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/AppsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/DeploymentsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/GroupsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/InfoResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/LeaderResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/PodsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/QueueResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/SpecInstancesResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/TasksResourceTest.scala
Labels: needs backport

#6799 Fix race condition causing deployment info to not be available
  changelog.md
  src/main/scala/mesosphere/marathon/core/deployment/DeploymentPlan.scala
  src/main/scala/mesosphere/marathon/core/deployment/impl/DeploymentManagerActor.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/DeploymentManagerActorTest.scala
Labels: backport-1.7

#6800 Fix race condition causing deployment info to not be available
  changelog.md
  src/main/scala/mesosphere/marathon/core/deployment/DeploymentPlan.scala
  src/main/scala/mesosphere/marathon/core/deployment/impl/DeploymentManagerActor.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/DeploymentManagerActorTest.scala
Labels: backport-1.6

#6801 Fix race condition causing deployment info to not be available
  changelog.md
  src/main/scala/mesosphere/marathon/core/deployment/DeploymentPlan.scala
  src/main/scala/mesosphere/marathon/core/deployment/impl/DeploymentManagerActor.scala
  src/test/scala/mesosphere/marathon/core/deployment/impl/DeploymentManagerActorTest.scala
Labels: backport-1.5

#6809 Handle wrapped requests
  src/main/scala/mesosphere/marathon/api/HttpTransferMetricsHandler.scala
Labels: needs backport

#6810 Fix master build by using a different version of deb pkg (#6798)
  build.sbt
Labels: backport-1.6

#6813 Handle wrapped requests
  src/main/scala/mesosphere/marathon/api/HttpTransferMetricsHandler.scala
Labels: backport-1.7

#6814 Handle wrapped requests
  src/main/scala/mesosphere/marathon/api/HttpTransferMetricsHandler.scala
Labels: backport-1.6
