Repository mesosphere/marathon, pull requests merged in 2019-08, with the labels that each got.

#7001 Added maintenance mode to info endpoint
  src/main/scala/mesosphere/marathon/api/v2/InfoResource.scala
Labels: backport-1.7

#6899 Remove redundant log lines to ease debugging (#6684)
  src/main/scala/mesosphere/marathon/core/task/jobs/impl/OverdueInstancesActor.scala
  src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceDelegate.scala
Labels: backport-1.7

#7006 Proper usage of absolute path (instead of relative) in the unit test
  src/test/scala/mesosphere/marathon/api/v2/json/DeploymentFormatsTest.scala
Labels: last one merges

#7008 Improved logging with regard to suppress/revive logic
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/ReviveOffersStreamLogic.scala
Labels: yolo

#6964 Update readiness-checks.md
  docs/docs/readiness-checks.md
  docs/docs/rest-api/public/api/v2/types/readinessCheck.raml
Labels: needs backport

#7019 1.7: Update documentation links to D2iQ url and changed pathes
  docs/docs/auth-access-ctrl.md
  docs/docs/fault-domain-awareness.md
  docs/docs/native-docker-private-registry.md
  docs/docs/networking.md
  docs/docs/pods.md
  docs/docs/waiting.md
Labels: backport-1.7, last one merges

#7018 1.8: Update documentation links to D2iQ url and changed pathes
  docs/docs/auth-access-ctrl.md
  docs/docs/fault-domain-awareness.md
  docs/docs/native-docker-private-registry.md
  docs/docs/networking.md
  docs/docs/pods.md
  docs/docs/waiting.md
Labels: backport-1.8, last one merges

#7017 Master: Update documentation links to D2iQ url and changed pathes
  docs/docs/auth-access-ctrl.md
  docs/docs/fault-domain-awareness.md
  docs/docs/native-docker-private-registry.md
  docs/docs/networking.md
  docs/docs/pods.md
  docs/docs/waiting.md
Labels: last one merges

#7023 Removed strict validation of external volume name
  README.md
  changelog.md
  docs/docs/external-volumes.md
  docs/docs/rest-api/public/api/v2/types/volumes.raml
  src/main/java/mesosphere/marathon/Protos.java
  src/main/proto/marathon.proto
  src/main/scala/mesosphere/marathon/api/serialization/ContainerSerializer.scala
  src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala
  src/main/scala/mesosphere/marathon/raml/VolumeConversion.scala
  src/main/scala/mesosphere/marathon/state/Volume.scala
  src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala
  src/test/scala/mesosphere/marathon/raml/VolumeConversionTest.scala
Labels: needs backport

#7024 Remove strict validation of external volume name (#7023)
  README.md
  changelog.md
  docs/docs/external-volumes.md
  docs/docs/rest-api/public/api/v2/types/volumes.raml
  src/main/java/mesosphere/marathon/Protos.java
  src/main/proto/marathon.proto
  src/main/scala/mesosphere/marathon/api/serialization/ContainerSerializer.scala
  src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala
  src/main/scala/mesosphere/marathon/raml/VolumeConversion.scala
  src/main/scala/mesosphere/marathon/state/Volume.scala
  src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala
  src/test/scala/mesosphere/marathon/raml/VolumeConversionTest.scala
Labels: backport-1.8

#7030 Fix `OfferMatcher` missing launch tokens (#7025)
  src/main/scala/mesosphere/marathon/core/matcher/manager/impl/OfferMatcherManagerDelegate.scala
Labels: backport-1.8, last one merges

#7033 Fix tests for master because of previously merged PR
  src/test/scala/mesosphere/marathon/api/v2/AppsResourceTest.scala
Labels: yolo

#7038 Fix some compilation warnings
  src/main/scala/mesosphere/marathon/api/MarathonRestModule.scala
  src/main/scala/mesosphere/marathon/api/v2/AppNormalization.scala
  src/main/scala/mesosphere/marathon/api/v2/validation/PodsValidation.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/deployment/impl/DeploymentActor.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorker.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerActor.scala
  src/main/scala/mesosphere/marathon/raml/CheckConversion.scala
  src/main/scala/mesosphere/marathon/raml/VolumeConversion.scala
  src/main/scala/mesosphere/marathon/stream/RateLimiterFlow.scala
  src/main/scala/mesosphere/mesos/TaskBuilder.scala
  src/test/scala/mesosphere/marathon/core/instance/TestInstanceBuilder.scala
  src/test/scala/mesosphere/marathon/tasks/InstanceOpFactoryImplTest.scala
Labels: last one merges

#7048 Improved IT logging
  tests/integration/src/test/scala/mesosphere/marathon/integration/UpgradeIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/MarathonTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/MesosTest.scala
Labels: yolo
