Repository mesosphere/marathon, pull requests merged in 2019-06, with the labels that each got.

#6932 Pin type-generator target and release to java 8
  type-generator/build.sbt
Labels: last one merges

#6931 Use 1.6.549 as baseline for upgrade tests.
  tests/integration/src/test/scala/mesosphere/marathon/integration/UpgradeIntegrationTest.scala
Labels: last one merges

#6922 Only match disk with profile if that profile is needed (#6916)
  changelog.md
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/main/scala/mesosphere/mesos/VolumeProfileMatcher.scala
  src/test/scala/mesosphere/mesos/VolumeProfileMatcherTest.scala
Labels: backport-1.7

#6935 Fix race condition after startup that prevents suppressing offers
  src/main/scala/mesosphere/marathon/core/matcher/reconcile/impl/OffersWantedForReconciliationActor.scala
  src/test/scala/mesosphere/marathon/core/matcher/reconcile/impl/OffersWantedForReconciliationActorTest.scala
Labels: backport-1.7

#6900 Provision AMI with Mesos 1.8.0
  Jenkinsfile
  Jenkinsfile.publishjars
  Jenkinsfile.release
  ami/AMI.md
  ami/install.bash
  ami/marathon-jenkins-ami.json
  project/Dependencies.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/MesosAppIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/UpgradeIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/facades/MesosFacade.scala
  tests/system/marathon_pods_tests.py
  tests/system/test_marathon_root.py
  tests/system/utils.py
Labels: hold merge

#6908 Add seccomp integration test
  src/main/scala/mesosphere/marathon/core/deployment/impl/TaskReplaceActor.scala
  tests/integration/src/test/resources/mesos/seccomp/default.json
  tests/integration/src/test/scala/mesosphere/marathon/integration/AgentGoneByOperatorIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/GpuSchedulingIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/RemoteRegionOffersIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/SeccompIntegratonTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/TaskUnreachableIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/MesosTest.scala
Labels: wip
