Repository mesosphere/marathon, pull requests merged in 2019-07, with the labels that each got.

#6951 Drop Debian 8 support.
  tests/package/Makefile
  tests/package/debian9/Dockerfile
  tests/package/mesos/Dockerfile
  tests/package/test.sc
  tools/packager/Makefile
Labels: backport-1.8

#6952 Drop Debian 8 support. (#6951)
  tests/package/Makefile
  tests/package/debian9/Dockerfile
  tests/package/mesos/Dockerfile
  tests/package/test.sc
  tools/packager/Makefile
Labels: backport-1.8

#6692 Add documentation for instances
  docs/articles/README.md
  docs/articles/applications.md
  docs/articles/deployments.md
  docs/articles/examples/requests/app-simple.json
  docs/articles/examples/responses/app-representation.json
  docs/articles/instance-lifecycle.md
  docs/articles/instances.md
  docs/articles/kill-selection.md
  docs/articles/pods.md
  docs/articles/services.md
  docs/articles/task-groups.md
  docs/articles/tasks.md
  docs/articles/tutorials/apps-scaling.md
  docs/articles/tutorials/instance-operations.md
  docs/articles/tutorials/pods-scaling.md
  docs/articles/unreachable-strategy.md
  docs/articles/upgrade-strategy.md
Labels: documentation

#6972 Only comment with collapsed details
  ci/githubClient.sc
Labels: needs backport

#6962 Exit with 111 if Marathon could not bind to address.
  docs/docs/exit-codes.md
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
Labels: needs backport

#6971 Update Marathon 1.5 in upgrade integration test. (#6963)
  tests/integration/src/test/scala/mesosphere/marathon/integration/UpgradeIntegrationTest.scala
Labels: backport-1.8

#6974 Exit with 111 if Marathon could not bind to address. (#6962)
  docs/docs/exit-codes.md
  src/main/scala/mesosphere/marathon/Main.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
Labels: backport-1.8

#6977 Log reasons if an offer is not matched
  src/main/scala/mesosphere/marathon/core/launchqueue/impl/TaskLauncherActor.scala
Labels: needs backport

#6976 Added maintenance mode to info endpoint
  src/main/scala/mesosphere/marathon/api/v2/InfoResource.scala
Labels: needs backport
