Repository mesosphere/marathon, pull requests merged in 2019-11, with the labels that each got.

#7094 Fix pod status for `Scheduled` instances with a goal `Stopped`
  changelog.md
  src/main/scala/mesosphere/marathon/raml/PodStatusConversion.scala
  src/test/scala/mesosphere/marathon/raml/PodStatusConversionTest.scala
Labels: needs backport

#7095 Fix pod status for `Scheduled` instances with a goal `Stopped`
  changelog.md
  src/main/scala/mesosphere/marathon/raml/PodStatusConversion.scala
  src/test/scala/mesosphere/marathon/raml/PodStatusConversionTest.scala
Labels: backport-1.8, last one merges

#7092 Fixed Path Parameter in resource
  src/main/scala/mesosphere/marathon/api/v2/QueueResource.scala
Labels: backport-1.7
