Repository mesosphere/marathon, pull requests merged in 2019-03, with the labels that each got.

#6820 Response asynchronously for all endpoints. (#6793)
  src/main/scala/mesosphere/marathon/api/AuthResource.scala
  src/main/scala/mesosphere/marathon/api/RestResource.scala
  src/main/scala/mesosphere/marathon/api/SystemResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppTasksResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppVersionsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/DeploymentsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/GroupsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/InfoResource.scala
  src/main/scala/mesosphere/marathon/api/v2/LeaderResource.scala
  src/main/scala/mesosphere/marathon/api/v2/PluginsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/PodsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/QueueResource.scala
  src/main/scala/mesosphere/marathon/api/v2/TasksResource.scala
  src/test/scala/mesosphere/marathon/api/AuthResourceTest.scala
  src/test/scala/mesosphere/marathon/api/SystemResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/AppVersionsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/AppsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/DeploymentsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/GroupsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/InfoResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/LeaderResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/PodsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/QueueResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/SpecInstancesResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/TasksResourceTest.scala
Labels: backport-1.7

#6821 Response asynchronously for all endpoints. (#6793)
  src/main/scala/mesosphere/marathon/api/AuthResource.scala
  src/main/scala/mesosphere/marathon/api/RestResource.scala
  src/main/scala/mesosphere/marathon/api/SystemResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppTasksResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppVersionsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/DeploymentsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/GroupsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/InfoResource.scala
  src/main/scala/mesosphere/marathon/api/v2/LeaderResource.scala
  src/main/scala/mesosphere/marathon/api/v2/PluginsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/PodsResource.scala
  src/main/scala/mesosphere/marathon/api/v2/QueueResource.scala
  src/main/scala/mesosphere/marathon/api/v2/TasksResource.scala
  src/test/scala/mesosphere/marathon/api/AuthResourceTest.scala
  src/test/scala/mesosphere/marathon/api/SystemResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/AppVersionsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/AppsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/DeploymentsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/GroupsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/InfoResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/LeaderResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/PodsResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/QueueResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/SpecInstancesResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/TasksResourceTest.scala
Labels: backport-1.6

#6816 Allow all users to execute /marathon/bin/marathon
  build.sbt
Labels: needs backport

#6823 Chown Marathon after installation.
  build.sbt
Labels: needs backport

#6818 Log the full offer in DEBUG mode
  src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala
Labels: needs backport

#6846 Allow all users to execute /marathon/bin/marathon
  build.sbt
Labels: backport-1.6

#6845 Allow all users to execute /marathon/bin/marathon
  build.sbt
Labels: backport-1.7

#6827 Map `tcp,udp` to `udp,tcp` during migration.
  src/main/scala/mesosphere/marathon/raml/NetworkConversion.scala
Labels: needs backport

#6860 Ignore out of date Jessie repos.
  tests/package/debian-systemd/Dockerfile
  tests/package/mesos/Dockerfile
  tests/package/test.sc
Labels: backport-1.5
