Repository mesosphere/marathon, pull requests merged in 2019-04, with the labels that each got.

#6862 Ignore out of date Jessie repos.
  tests/package/debian-systemd/Dockerfile
  tests/package/mesos/Dockerfile
  tests/package/test.sc
Labels: backport-1.6

#6861 Ignore out of date Jessie repos. (#6857)
  tests/package/README.md
  tests/package/debian8/Dockerfile
  tests/package/mesos/Dockerfile
  tests/package/test.sc
Labels: backport-1.7

#6855 Map `tcp,udp` to `udp,tcp` during migration. (#6827)
  src/main/scala/mesosphere/marathon/raml/NetworkConversion.scala
  src/test/scala/mesosphere/marathon/raml/NetworkConversionTest.scala
Labels: backport-1.7

#6854 Map `tcp,udp` to `udp,tcp` during migration. (#6827)
  src/main/scala/mesosphere/marathon/raml/NetworkConversion.scala
  src/test/scala/mesosphere/marathon/raml/NetworkConversionTest.scala
Labels: backport-1.6

#6876 Do not fail on offers with RAW and BLOCK disk types
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/test/scala/mesosphere/marathon/test/MarathonTestHelper.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
Labels: needs backport

#6883 Do not fail on offers with RAW and BLOCK disk types (#6876) (Backport)
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/test/scala/mesosphere/marathon/test/MarathonTestHelper.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
Labels: backport-1.6

#6884 Do not fail on offers with RAW and BLOCK disk types (#6876) (Backport)
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/test/scala/mesosphere/marathon/test/MarathonTestHelper.scala
  src/test/scala/mesosphere/mesos/ResourceMatcherTest.scala
Labels: backport-1.7

#6879 Fix restarting unhealthy instances.
  src/main/scala/mesosphere/marathon/core/health/HealthModule.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegate.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/AppDeployIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/HealthCheckIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/IntegrationHealthCheck.scala
  tests/system/marathon_common_tests.py
Labels: needs backport

#6873 Introduced global throttling for Marathon health checks.
  changelog.md
  src/main/scala/mesosphere/marathon/MarathonConf.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/health/HealthModule.scala
  src/main/scala/mesosphere/marathon/core/health/HealthResult.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorker.scala
  src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegate.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManagerTest.scala
  src/test/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegateTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/AppDeployIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/HealthCheckIntegrationTest.scala
Labels: backport-1.7

#6874 Introduced global throttling for Marathon health checks
  changelog.md
  src/main/scala/mesosphere/marathon/MarathonConf.scala
  src/main/scala/mesosphere/marathon/core/CoreModuleImpl.scala
  src/main/scala/mesosphere/marathon/core/health/HealthModule.scala
  src/main/scala/mesosphere/marathon/core/health/HealthResult.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckWorker.scala
  src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerActor.scala
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegate.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckActorTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManagerTest.scala
  src/test/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerDelegateTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/AppDeployIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/HealthCheckIntegrationTest.scala
Labels: backport-1.6

#6882 Fix restarting unhealthy instances.
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  src/test/scala/mesosphere/marathon/integration/HealthCheckIntegrationTest.scala
Labels: backport-1.5

#6878 Fix metrics prefix name in the docs
  docs/docs/metrics.md
Labels: fluffy, last one merges

#6890 Update changelog for 1.5.15
  changelog.md
Labels: last one merges

#6895 Introduce new exit error code when the framework was removed from Mesos
  docs/docs/exit-codes.md
  src/main/scala/mesosphere/marathon/MarathonScheduler.scala
  src/main/scala/mesosphere/marathon/core/base/CrashStrategy.scala
Labels: last one merges

#6897 Fix docs formatting
  docs/docs/networking.md
Labels: last one merges

#6898 Add simple troubleshooting sections for exit codes
  docs/docs/exit-codes.md
Labels: documentation
