Repository mesosphere/marathon, pull requests merged in 2019-05, with the labels that each got.

#6903 Bump Mesos jar to 1.8.0 release
  project/Dependencies.scala
Labels: last one merges

#6910 Add TASK_UNKNOWN to the valid mesos task status enums
  docs/docs/rest-api/public/api/v2/types/stringTypes.raml
Labels: needs backport

#6911 Add TASK_UNKNOWN to the valid mesos task status enums (#6910)
  docs/docs/rest-api/public/api/v2/types/stringTypes.raml
Labels: backport-1.7

#6912 Add TASK_UNKNOWN to the valid mesos task status enums (#6910)
  docs/docs/rest-api/public/api/v2/types/stringTypes.raml
Labels: backport-1.6

#6916 Only match disk with profile if that profile is needed
  src/main/scala/mesosphere/mesos/ResourceMatcher.scala
  src/main/scala/mesosphere/mesos/VolumeProfileMatcher.scala
  src/test/scala/mesosphere/mesos/VolumeProfileMatcherTest.scala
Labels: needs backport

#6926 Remove `mesos-client` module
  build.sbt
  mesos-client/README.md
  mesos-client/src/main/protobuf/mesos/v1/mesos.proto
  mesos-client/src/main/protobuf/mesos/v1/scheduler/scheduler.proto
  mesos-client/src/main/scala/mesosphere/mesos/client/MesosCalls.scala
  mesos-client/src/main/scala/mesosphere/mesos/client/MesosClient.scala
  mesos-client/src/main/scala/mesosphere/mesos/client/MesosConnectionContext.scala
  mesos-client/src/main/scala/mesosphere/mesos/client/StrictLoggingFlow.scala
  mesos-client/src/main/scala/mesosphere/mesos/conf/MesosClientConf.scala
  mesos-client/src/main/scala/mesosphere/mesos/examples/UselessFramework.scala
  mesos-client/src/test/scala/mesosphere/mesos/client/MesosClientIntegrationTest.scala
Labels: last one merges
