Repository mesosphere/marathon, pull requests merged in 2020-04, with the labels that each got.

#7163 Defer loading of instances.
  src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceTrackerActor.scala
Labels: backport-1.8

#7168 Use bash for release pipeline.
  Jenkinsfile.release
  tools/packager/Makefile
Labels: backport-1.9

#7169 Use bash for release pipeline.
  Jenkinsfile.release
  tools/packager/Makefile
  tools/packager/bin/upload-package
Labels: backport-1.8

#7175 Only crash HealthCheckActor if stream for the current incarnation of HealthCheckActor stopped
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
Labels: backport-1.9

#7176 Only crash HealthCheckActor if stream for the current incarnation of HealthCheckActor stopped
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
Labels: backport-1.8

#7178 Fix issue that causes infinite restart of HealthCheckActor
  Jenkinsfile
  Jenkinsfile.release
  ci/dataDogClient.sc
  ci/githubClient.sc
  ci/pipeline
  src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/UpgradeIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/facades/MesosFacade.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/MesosTest.scala
  tests/system/common.py
  tests/system/marathon_pods_tests.py
  tests/system/test_marathon_root.py
  tests/system/utils.py
Labels: backport-1.6
