Repository mesosphere/marathon, pull requests merged in 2020-01, with the labels that each got.

#7119 Add compatibility mode query param for /tasks endpoint to have output compatible with 1.4 (#6784)
  src/main/scala/mesosphere/marathon/api/EndpointsHelper.scala
  src/main/scala/mesosphere/marathon/api/v2/AppTasksResource.scala
  src/main/scala/mesosphere/marathon/api/v2/MarathonCompatibility.scala
  src/main/scala/mesosphere/marathon/api/v2/TasksResource.scala
  src/test/scala/mesosphere/marathon/api/v2/SpecInstancesResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/TasksResourceTest.scala
Labels: backport-1.6

#7122 Move storage tool to Marathon repo
  Jenkinsfile
  Jenkinsfile.publishjars
  Jenkinsfile.release
  ami/AMI.md
  ami/install.bash
  ami/main.tf
  ami/marathon-jenkins-ami.json
  ci/dataDogClient.sc
  ci/pipeline
  tools/storage/.gitignore
  tools/storage/BUILDING.md
  tools/storage/LICENSE
  tools/storage/Makefile
  tools/storage/README.md
  tools/storage/ammonite-docker/Dockerfile
  tools/storage/src/Dockerfile
  tools/storage/src/bin/storage-tool.sh
  tools/storage/src/lib/bindings.sc
  tools/storage/src/lib/dsl.sc
  tools/storage/src/lib/helpers.sc
  tools/storage/src/lib/load-jar.sc
  tools/storage/src/lib/predef.sc
  tools/storage/src/lib/version.sc
Labels: backport-1.8

#7114 Allow unreachable instances to actually be expunged immediately
  changelog.md
  project/build.properties
  src/main/scala/mesosphere/marathon/core/instance/Instance.scala
  src/main/scala/mesosphere/marathon/core/instance/update/InstanceUpdater.scala
  src/main/scala/mesosphere/marathon/core/task/jobs/impl/ExpungeOverdueLostTasksActor.scala
  src/main/scala/mesosphere/marathon/state/Timestamp.scala
  src/test/scala/mesosphere/marathon/core/appinfo/TaskCountsTest.scala
  src/test/scala/mesosphere/marathon/core/appinfo/impl/AppInfoBaseDataTest.scala
  src/test/scala/mesosphere/marathon/core/health/impl/HealthCheckWorkerTest.scala
  src/test/scala/mesosphere/marathon/core/instance/InstanceStateTest.scala
  src/test/scala/mesosphere/marathon/core/instance/InstanceTest.scala
  src/test/scala/mesosphere/marathon/core/instance/TestInstanceBuilder.scala
  src/test/scala/mesosphere/marathon/core/instance/update/InstanceUpdateOpResolverTest.scala
  src/test/scala/mesosphere/marathon/core/instance/update/InstanceUpdaterTest.scala
  src/test/scala/mesosphere/marathon/test/MarathonTestHelper.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/RemoteRegionOffersIntegrationTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/facades/MesosFacade.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/facades/MesosFormats.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/MarathonTest.scala
  tests/integration/src/test/scala/mesosphere/marathon/integration/setup/MesosTest.scala
Labels: backport-1.8

#7126 Add `?containerNetworks` querystring parameter to /v2/tasks text output
  changelog.md
  docs/docs/rest-api/public/api/v2/apps.raml
  docs/docs/rest-api/public/api/v2/tasks.raml
  src/main/scala/mesosphere/marathon/api/EndpointsHelper.scala
  src/main/scala/mesosphere/marathon/api/v2/AppTasksResource.scala
  src/main/scala/mesosphere/marathon/api/v2/TasksResource.scala
  src/test/scala/mesosphere/marathon/api/EndpointsHelperTest.scala
  src/test/scala/mesosphere/marathon/api/v2/SpecInstancesResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/TasksResourceTest.scala
Labels: backport-1.8

#7127 Add `?containerNetworks` querystring parameter to /v2/tasks text output
  changelog.md
  docs/docs/rest-api/public/api/v2/apps.raml
  docs/docs/rest-api/public/api/v2/tasks.raml
  src/main/scala/mesosphere/marathon/api/EndpointsHelper.scala
  src/main/scala/mesosphere/marathon/api/v2/AppTasksResource.scala
  src/main/scala/mesosphere/marathon/api/v2/TasksResource.scala
  src/test/scala/mesosphere/marathon/api/EndpointsHelperTest.scala
  src/test/scala/mesosphere/marathon/api/v2/SpecInstancesResourceTest.scala
  src/test/scala/mesosphere/marathon/api/v2/TasksResourceTest.scala
Labels: backport-1.7
